blackjack = Hash.new
blackjack = {"soft" => {2 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Double or Hit",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        3 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Double or Hit",
                              18 => "Double or Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        4 => {13 => "Double or Hit",
                              14 => "Double or Hit",
                              15 => "Double or Hit",
                              16 => "Double or Hit",
                              17 => "Double or Hit",
                              18 => "Double or Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        5 => {13 => "Double or Hit",
                              14 => "Double or Hit",
                              15 => "Double or Hit",
                              16 => "Double or Hit",
                              17 => "Double or Hit",
                              18 => "Double or Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        6 => {13 => "Double or Hit",
                              14 => "Double or Hit",
                              15 => "Double or Hit",
                              16 => "Double or Hit",
                              17 => "Double or Hit",
                              18 => "Double or Stand",
                              19 => "Double or Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        7 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Hit",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        8 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Hit",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        9 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Hit",
                              18 => "Hit",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                       10 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Hit",
                              18 => "Hit",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                       11 => {13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Hit",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"}},
              "hard" => {2 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Double or Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Stand",
                              14 => "Stand",
                              15 => "Stand",
                              16 => "Stand",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand",},
                         3 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Double or Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Stand",
                              14 => "Stand",
                              15 => "Stand",
                              16 => "Stand",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                         4 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Double or Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Stand",
                              13 => "Stand",
                              14 => "Stand",
                              15 => "Stand",
                              16 => "Stand",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                         5 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Double or Hit",
                               9 => "Double or Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Stand",
                              13 => "Stand",
                              14 => "Stand",
                              15 => "Stand",
                              16 => "Stand",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                         6 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Double or Hit",
                               9 => "Double or Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Stand",
                              13 => "Stand",
                              14 => "Stand",
                              15 => "Stand",
                              16 => "Stand",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                         7 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                         8 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                         9 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Hit",
                              10 => "Double or Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        10 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Hit",
                              10 => "Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"},
                        11 => {5 => "Hit",
                               6 => "Hit",
                               7 => "Hit",
                               8 => "Hit",
                               9 => "Hit",
                              10 => "Hit",
                              11 => "Double or Hit",
                              12 => "Hit",
                              13 => "Hit",
                              14 => "Hit",
                              15 => "Hit",
                              16 => "Hit",
                              17 => "Stand",
                              18 => "Stand",
                              19 => "Stand",
                              20 => "Stand",
                              21 => "Stand"}},
         "pairs" => {2 => {"2,2" => "Split",
                           "3,3" => "Split",
                           "4,4" => "Hit",
                           "5,5" => "Double or Hit",
                           "6,6" => "Split",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     3 => {"2,2" => "Split",
                           "3,3" => "Split",
                           "4,4" => "Hit",
                           "5,5" => "Double or Hit",
                           "6,6" => "Split",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     4 => {"2,2" => "Split",
                           "3,3" => "Split",
                           "4,4" => "Split",
                           "5,5" => "Double or Hit",
                           "6,6" => "Split",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     5 => {"2,2" => "Split",
                           "3,3" => "Split",
                           "4,4" => "Split",
                           "5,5" => "Double or Hit",
                           "6,6" => "Split",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     6 => {"2,2" => "Split",
                           "3,3" => "Split",
                           "4,4" => "Split",
                           "5,5" => "Double or Hit",
                           "6,6" => "Split",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     7 => {"2,2" => "Split",
                           "3,3" => "Split",
                           "4,4" => "Hit",
                           "5,5" => "Double or Hit",
                           "6,6" => "Split",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Stand",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     8 => {"2,2" => "Hit",
                           "3,3" => "Split",
                           "4,4" => "Hit",
                           "5,5" => "Double or Hit",
                           "6,6" => "Hit",
                           "7,7" => "Split",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                     9 => {"2,2" => "Hit",
                           "3,3" => "Hit",
                           "4,4" => "Hit",
                           "5,5" => "Double or Hit",
                           "6,6" => "Hit",
                           "7,7" => "Hit",
                           "8,8" => "Split",
                           "9,9" => "Split",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                    10 => {"2,2" => "Hit",
                           "3,3" => "Hit",
                           "4,4" => "Hit",
                           "5,5" => "Hit",
                           "6,6" => "Hit",
                           "7,7" => "Stand",
                           "8,8" => "Split",
                           "9,9" => "Stand",
                         "10,10" => "Stand",
                         "11,11" => "Split"},
                    11 => {"2,2" => "Hit",
                           "3,3" => "Hit",
                           "4,4" => "Hit",
                           "5,5" => "Hit",
                           "6,6" => "Hit",
                           "7,7" => "Hit",
                           "8,8" => "Split",
                           "9,9" => "Stand",
                         "10,10" => "Stand",
                         "11,11" => "Split"}}}

def evaluate(card)
card == "A" ? card = 11 : card
end

puts "Play some blackjack! I'll give you the best strategy for any hand."
puts "Enter your two cards, and the dealer's card."
puts "For face cards, please enter 10."
puts "For an ace, please enter A."
puts "------"
puts
puts "What is your first card?"
first = gets.chomp
first_card = evaluate(first).to_i

puts "What is your second card?"
second = gets.chomp
second_card = evaluate(second).to_i

player_hand = first_card + second_card

puts "What is the dealer's card?"
dealer = gets.chomp
dealer_card = evaluate(dealer).to_i

if first_card == second_card
  player_hand = "#{first_card.to_s},#{second_card.to_s}"
  puts "You should #{blackjack["pairs"][dealer_card][player_hand]}"
elsif first_card == 11 || second_card == 11
  puts "You should #{blackjack["soft"][dealer_card][player_hand]}"
else
  puts "You should #{blackjack["hard"][dealer_card][player_hand]}"
end
